### ISSUE TITLE
Linear Regression Example

### ISSUE THREAD

**Issue by franalgaba** [gizatechxyz/orion#21] opened 2023-04-11 13:44 UTC

**Comment by BemTG** [comment] 2023-08-08 21:38
Hello @franalgaba , hope all is well. Is this supposed to be part of the Hub or Academy or both.  As I have implemented a Linear Regression model using Orion lib [here](https://github.com/BemTG/Verifiable-Linear-Regression-).  Do let me know where it can fit or if I should expand it and write a tutorial on similar to the MNIST example .

**Comment by raphaelDkhn** [comment] 2023-08-09 06:07
This is awesome, thanks @BemTG!!! 

It will be part of the Orion Hub, since it's a model! I'll add it to the Hub curated section in the doc. Soon, when we launch the website, your template will appear in the marketplace section.

If you'd like to expand it and write a tutorial, that would be great! So we can add it to Orion Academy. 

Thanks again for your contributions!

**Comment by BemTG** [comment] 2023-08-10 17:47
Glad to contribute and be part of an exciting project pushing the boundaries of the use cases of both Blockchain and ML 😃 . I'll make sure to expand it further and make a PR in the tutorials section @raphaelDkhn  👍

**Closed** 2023-08-16 07:50 UTC
Labels: help wanted, good first issue, community
